#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# License: GNU General Public License v2
# (c) 2014 Sixt GmbH & Co. Autovermietung KG
#          Matthias Haehnel <matthias.haehnel@sixt.com>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_rdp_arguments(params):
    settings = params[0]

    if 'hostname' in settings:
        args = "-H %s" % quote_shell_string(settings['hostname'])
    else:
        args = "-H $HOSTADDRESS$"

    if "port" in settings:
        args += " -p %d" % settings["port"]

    if "warning" in settings:
        args += ' -w %d' % settings["timeout"]

    if "critical" in settings:
        args += ' -c %d' % settings["timeout"]

    return args

def check_rdp_description(params):
    settings = params[0]

    description = "RDP"

    if 'hostname' in settings and '$' not in settings['hostname']:
        description += " %s" % settings['hostname']

    if 'port' in settings:
        description += " Port %s" % settings['port']

    return description

active_check_info['rdp'] = {
    "command_line"        : '$USER2$/check_x224 $ARG1$',
    "argument_function"   : check_rdp_arguments,
    "service_description" : check_rdp_description ,
    "has_perfdata"        : True,
}
